### ISSUE TITLE
use dep for dependency vendoring

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-cli#54]

**Comment by timfallmk** [comment]
I was trying to avoid this for the moment, but if we're going to add in the sdk it'll be necessary.

**Comment by edaniszewski** [comment]
Genuine question - is there a benefit to avoiding vendoring?

**Comment by timfallmk** [comment]
You're tempting me to go on a long rant.

Avoiding that, there are two major reasons:
1. Dependency management is a mess, and Golang's dependency management is it's own special kind of hell. While I think `go dep` improves a lot on the other options, it's still far from good. On top of that there are number of side cases and issues with it that can cause problems.
2. Aside from the problems with vendoring in Golang, there's the general, philosophical problems with vendoring. It tends to allow laziness and gives people an excuse not to update their code. The benefit is that everything you depend on stays the same. The downside is that updates can go un dealt with. I don't personally see that being a problem here, but we would have to keep on the updates.

I got away with it here by using `gopkg.in` for the one branched dependency, and directly importing everything else. Makes it much cleaner, but that only works because it has such limited dependencies. So I agree with you that it will need to happen if we're going to expand the functionality.
